Breaking: drop node v10/v13/v15 (refs eslint/eslint#14023)
eslint/eslintrc pull request #37
Opened 2021-06-09 02:48 UTC by aladdin-add

2021-06-09 03:01 UTC, snitin315 reviewed
It looks like we have a small lint issue.

2021-06-09 03:12 UTC, snitin315 approved these changes
LGTM 🚀

2021-06-09 03:36 UTC, ljharb requested changes

2021-06-09 03:36 UTC, ljharb commented on .github/workflows/ci.yml
> +        node: [16.x, 14.x, 12.x, "12.22.0"]
```suggestion
        node: [16.x, 14.x, "14.17.0", 12.x, "12.22.0"]
```

2021-06-09 03:36 UTC, ljharb commented on package.json
> +    "node": "^12.22.0 || ^14.17.0 || >=16.0.0"
beware the >=, that will force v17 etc whether you intend it or not

2021-06-12 00:58 UTC, nzakas commented
Let’s make sure we sync these changes with the final changes in the eslint repo

2021-08-04 18:18 UTC, nzakas approved these changes

2021-08-04 18:18 UTC, merged